name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Create project directory if it doesn't exist
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "mkdir -p ~/projects/wordle"

      - name: Clean
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "rm -rf ~/projects/wordle/*"

      - name: Copy files to VPS
        run: |
          scp -i ~/.ssh/id_rsa -r ./* ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:~/projects/wordle
        env:
          SSH_AUTH_SOCK: /tmp/ssh_auth.sock

      - name: Install dependencies
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "cd ~/projects/wordle && source ~/.nvm/nvm.sh && npm ci"

      - name: Restart application
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "source ~/.nvm/nvm.sh && pm2 restart all || pm2 start ~/projects/wordle/index.js --name 'wordle'"
